import { listTimezones } from '../utils/datetime';

const API_ROOT = 'http://localhost:5000/api';

const moneyField = {
  step: '0.01',
};

const timezoneOptions = listTimezones().map((tz) => ({ label: tz, value: tz }));

export const MASTER_DATA_MODULES = {
  dashboard: {
    key: 'dashboard',
    group: 'Overview',
    label: 'Dashboard',
    entityLabel: 'Dashboard',
    title: 'Dashboard',
    description: 'Real-time overview of sales, purchases, production, and cash position.',
    apiBase: `${API_ROOT}/misc/dashboard`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'dashboard',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  categories: {
    key: 'categories',
    group: 'Master Data',
    label: 'Categories',
    entityLabel: 'Category',
    title: 'Categories',
    description: 'Organize the master catalog used across products and finance.',
    apiBase: `${API_ROOT}/master/categories`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Category',
    saveButtonLabel: 'Save Category',
    emptyState: {
      title: 'No categories yet',
      description: 'Create the first category to start structuring your catalog.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Category name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'id', label: 'ID', sortable: true, width: '84px' },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  products: {
    key: 'products',
    group: 'Master Data',
    label: 'Products',
    entityLabel: 'Product',
    title: 'Products',
    description: 'Maintain product master records used by procurement, sales, and inventory.',
    apiBase: `${API_ROOT}/master/products`,
    searchFields: ['name', 'product_code', 'barcode'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Product',
    saveButtonLabel: 'Save Product',
    emptyState: {
      title: 'No products yet',
      description: 'Create a product to start managing stock and pricing.',
    },
    lookups: [
      {
        key: 'categories',
        apiBase: `${API_ROOT}/master/categories`,
        valueKey: 'id',
        labelKey: 'name',
      },
      {
        key: 'productTypes',
        apiBase: `${API_ROOT}/master/product-types`,
        valueKey: 'id',
        labelKey: 'name',
      },
    ],
    fields: [
      { key: 'product_code', label: 'Product Code', type: 'text', placeholder: 'Optional product code' },
      { key: 'barcode', label: 'Barcode', type: 'text', placeholder: 'Optional barcode' },
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Product name' },
      {
        key: 'category_id',
        label: 'Category',
        type: 'select',
        placeholder: 'Select a category',
        lookupKey: 'categories',
        valueType: 'number',
      },
      { key: 'group_name', label: 'Group', type: 'text', placeholder: 'Optional group name' },
      { key: 'unit', label: 'Unit', type: 'text', placeholder: 'Optional unit' },
      { key: 'contains', label: 'Contains', type: 'textarea', placeholder: 'Optional ingredients or packaging note' },
      { key: 'min_stock_level', label: 'Minimum Stock', type: 'number', ...moneyField, placeholder: '0.00' },
      {
        key: 'product_type_id',
        label: 'Product Type',
        type: 'select',
        required: true,
        placeholder: 'Select a product type',
        lookupKey: 'productTypes',
        valueType: 'number',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ],
    // Pricing is set separately from creation (see the "Set Price" row action) -
    // cost/markup/selling price live in their own dialog, not the create/edit form.
    pricingFields: [
      { key: 'cost_price', label: 'Cost Price', type: 'number', ...moneyField, placeholder: '0.00' },
      {
        key: 'markup_type',
        label: 'Markup Type',
        type: 'select',
        options: [
          { label: 'Fixed', value: 'fixed' },
          { label: 'Percentage', value: 'percentage' },
        ],
      },
      { key: 'markup_value', label: 'Markup Value', type: 'number', ...moneyField, placeholder: '0.00' },
    ],
    actions: ['set-price', 'quantity-pricing'],
    // Enables row checkboxes + the "Set Price for N selected" bulk action.
    bulkPricing: true,
    columns: [
      { key: 'product_code', label: 'Code', sortable: true },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'category_id', label: 'Category' },
      { key: 'product_type_id', label: 'Product Type' },
      { key: 'selling_price', label: 'Price', align: 'right' },
      { key: 'status', label: 'Status', sortable: true },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Code A-Z', value: 'product_code-asc' },
      { label: 'Code Z-A', value: 'product_code-desc' },
      { label: 'Price low-high', value: 'selling_price-asc' },
      { label: 'Price high-low', value: 'selling_price-desc' },
    ],
  },
  'pricing-tiers': {
    key: 'pricing-tiers',
    group: 'Master Data',
    label: 'Quantity Pricing',
    entityLabel: 'Pricing Tier',
    title: 'Quantity Pricing',
    description: 'Every quantity-based price tier across all products, in one place.',
    apiBase: `${API_ROOT}/pricing/tiers`,
    searchFields: ['product_name', 'product_code'],
    defaultSort: { sortBy: 'product_name', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: {
      title: 'No quantity pricing set yet',
      description: 'Open a product and use "Quantity Pricing" to add tiers.',
    },
    readOnly: true,
    actions: ['quantity-pricing'],
    fields: [],
    columns: [
      { key: 'product_name', label: 'Product', sortable: true },
      { key: 'product_code', label: 'Code' },
      { key: 'min_quantity', label: 'From Qty', align: 'right', sortable: true },
      { key: 'unit_price', label: 'Unit Price', align: 'right', sortable: true },
    ],
    sortOptions: [
      { label: 'Product A-Z', value: 'product_name-asc' },
      { label: 'Product Z-A', value: 'product_name-desc' },
      { label: 'Quantity low-high', value: 'min_quantity-asc' },
      { label: 'Quantity high-low', value: 'min_quantity-desc' },
      { label: 'Price low-high', value: 'unit_price-asc' },
      { label: 'Price high-low', value: 'unit_price-desc' },
    ],
  },
  suppliers: {
    key: 'suppliers',
    group: 'Master Data',
    label: 'Suppliers',
    entityLabel: 'Supplier',
    title: 'Suppliers',
    description: 'Track supplier records and contact details used by procurement.',
    apiBase: `${API_ROOT}/master/suppliers`,
    searchFields: ['name', 'contact_person', 'phone', 'email'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Supplier',
    saveButtonLabel: 'Save Supplier',
    emptyState: {
      title: 'No suppliers yet',
      description: 'Add a supplier to begin managing procurement records.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Supplier name' },
      { key: 'contact_person', label: 'Contact Person', type: 'text', placeholder: 'Optional contact person' },
      { key: 'phone', label: 'Phone', type: 'text', placeholder: 'Optional phone number' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'Optional email address' },
      { key: 'address', label: 'Address', type: 'textarea', placeholder: 'Optional address' },
      { key: 'outstanding_balance', label: 'Outstanding Balance', type: 'number', ...moneyField, placeholder: '0.00', zeroDefault: true },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'contact_person', label: 'Contact Person' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'outstanding_balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'outstanding_balance-asc' },
      { label: 'Balance high-low', value: 'outstanding_balance-desc' },
    ],
  },
  customers: {
    key: 'customers',
    group: 'Master Data',
    label: 'Customers',
    entityLabel: 'Customer',
    title: 'Customers',
    description: 'Maintain customer records used by sales and accounts receivable.',
    apiBase: `${API_ROOT}/master/customers`,
    searchFields: ['name', 'contact_person', 'phone', 'email', 'customer_type'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Customer',
    saveButtonLabel: 'Save Customer',
    emptyState: {
      title: 'No customers yet',
      description: 'Create a customer to start managing sales accounts.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Customer name' },
      { key: 'customer_type', label: 'Customer Type', type: 'text', placeholder: 'Retail, wholesale, distributor...' },
      { key: 'contact_person', label: 'Contact Person', type: 'text', placeholder: 'Optional contact person' },
      { key: 'phone', label: 'Phone', type: 'text', placeholder: 'Optional phone number' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'Optional email address' },
      { key: 'address', label: 'Address', type: 'textarea', placeholder: 'Optional address' },
      { key: 'credit_limit', label: 'Credit Limit', type: 'number', ...moneyField, placeholder: '0.00', zeroDefault: true },
      { key: 'outstanding_balance', label: 'Outstanding Balance', type: 'number', ...moneyField, placeholder: '0.00', zeroDefault: true },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'customer_type', label: 'Type' },
      { key: 'contact_person', label: 'Contact Person' },
      { key: 'phone', label: 'Phone' },
      { key: 'outstanding_balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'outstanding_balance-asc' },
      { label: 'Balance high-low', value: 'outstanding_balance-desc' },
    ],
  },
  warehouses: {
    key: 'warehouses',
    group: 'Master Data',
    label: 'Warehouses',
    entityLabel: 'Warehouse',
    title: 'Warehouses',
    description: 'Manage warehouse locations and fulfillment destinations.',
    apiBase: `${API_ROOT}/master/warehouses`,
    searchFields: ['name', 'location', 'warehouse_type'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Warehouse',
    saveButtonLabel: 'Save Warehouse',
    emptyState: {
      title: 'No warehouses yet',
      description: 'Create a warehouse to organize inventory locations.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Warehouse name' },
      { key: 'location', label: 'Location', type: 'text', placeholder: 'Optional location' },
      { key: 'warehouse_type', label: 'Warehouse Type', type: 'text', placeholder: 'Raw material, finished goods...' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'location', label: 'Location' },
      { key: 'warehouse_type', label: 'Type' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  accounts: {
    key: 'accounts',
    group: 'Master Data',
    label: 'Accounts',
    entityLabel: 'Account',
    title: 'Accounts',
    description: 'Maintain cash and bank accounts used by finance and payments.',
    apiBase: `${API_ROOT}/master/accounts`,
    searchFields: ['name', 'bank_name', 'account_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Account',
    saveButtonLabel: 'Save Account',
    emptyState: {
      title: 'No accounts yet',
      description: 'Add a finance account to track balances and transactions.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Account name' },
      { key: 'account_type', label: 'Account Type', type: 'text', placeholder: 'Cash or bank' },
      { key: 'account_number', label: 'Account Number', type: 'text', placeholder: 'Optional account number' },
      { key: 'bank_name', label: 'Bank Name', type: 'text', placeholder: 'Optional bank name' },
      { key: 'balance', label: 'Balance', type: 'number', ...moneyField, placeholder: '0.00', zeroDefault: true },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'account_type', label: 'Type' },
      { key: 'account_number', label: 'Account Number' },
      { key: 'bank_name', label: 'Bank' },
      { key: 'balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'balance-asc' },
      { label: 'Balance high-low', value: 'balance-desc' },
      { label: 'Bank A-Z', value: 'bank_name-asc' },
      { label: 'Bank Z-A', value: 'bank_name-desc' },
    ],
  },
  'payment-methods': {
    key: 'payment-methods',
    group: 'Master Data',
    label: 'Payment Methods',
    entityLabel: 'Payment Method',
    title: 'Payment Methods',
    description: 'Manage the payment channels available in the system.',
    apiBase: `${API_ROOT}/master/payment-methods`,
    searchFields: ['name', 'code', 'description'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Payment Method',
    saveButtonLabel: 'Save Payment Method',
    emptyState: {
      title: 'No payment methods yet',
      description: 'Create the first payment method used by the organization.',
    },
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true, placeholder: 'Payment code' },
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Payment method name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
      { key: 'is_active', label: 'Active', type: 'checkbox' },
      { key: 'affects_cash_drawer', label: 'Counts as Cash (POS drawer)', type: 'checkbox' },
    ],
    columns: [
      { key: 'code', label: 'Code', sortable: true },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'is_active', label: 'Status' },
      { key: 'affects_cash_drawer', label: 'Cash Drawer' },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Code A-Z', value: 'code-asc' },
      { label: 'Code Z-A', value: 'code-desc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  'purchase-orders': {
    key: 'purchase-orders',
    group: 'Procurement',
    label: 'Purchase Orders',
    entityLabel: 'Purchase Order',
    title: 'Purchase Orders',
    description: 'Create and review purchase orders for suppliers.',
    apiBase: `${API_ROOT}/procurement/orders`,
    searchFields: ['po_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Purchase Order',
    saveButtonLabel: 'Save Purchase Order',
    emptyState: {
      title: 'No purchase orders yet',
      description: 'Create a purchase order to begin procurement workflows.',
    },
    renderType: 'procurement',
    defaultTab: 'orders',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'PO Number A-Z', value: 'po_number-asc' },
      { label: 'PO Number Z-A', value: 'po_number-desc' },
    ],
  },
  'purchase-vouchers': {
    key: 'purchase-vouchers',
    group: 'Procurement',
    label: 'Purchase Vouchers',
    entityLabel: 'Purchase Voucher',
    title: 'Purchase Vouchers',
    description: 'Record receipts and voucher details for received goods.',
    apiBase: `${API_ROOT}/procurement/vouchers`,
    searchFields: ['voucher_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Purchase Voucher',
    saveButtonLabel: 'Save Purchase Voucher',
    emptyState: {
      title: 'No purchase vouchers yet',
      description: 'Create a voucher to track receipts and payments.',
    },
    renderType: 'procurement',
    defaultTab: 'vouchers',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Voucher Number A-Z', value: 'voucher_number-asc' },
      { label: 'Voucher Number Z-A', value: 'voucher_number-desc' },
    ],
  },
  'report-sales-by-category': {
    key: 'report-sales-by-category',
    group: 'Reports',
    label: 'Sales by Category',
    entityLabel: 'Report',
    title: 'Sales by Category',
    description: 'Revenue and margin by product category.',
    apiBase: `${API_ROOT}/reports/sales-by-category`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'sales-by-category',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-payment-method-analysis': {
    key: 'report-payment-method-analysis',
    group: 'Reports',
    label: 'Payment Method Analysis',
    entityLabel: 'Report',
    title: 'Payment Method Analysis',
    description: 'How customers are paying, by tender type.',
    apiBase: `${API_ROOT}/reports/payment-method-analysis`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'payment-method-analysis',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'purchase-returns': {
    key: 'purchase-returns',
    group: 'Procurement',
    label: 'Purchase Returns',
    entityLabel: 'Purchase Return',
    title: 'Purchase Returns',
    description: 'Record goods sent back to a supplier and debit notes.',
    apiBase: `${API_ROOT}/procurement/returns`,
    searchFields: ['return_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Return',
    saveButtonLabel: 'Save Return',
    emptyState: {
      title: 'No purchase returns yet',
      description: 'Record a return when goods go back to a supplier.',
    },
    renderType: 'procurement',
    defaultTab: 'returns',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
    ],
  },
  'sale-orders': {
    key: 'sale-orders',
    group: 'Sales',
    label: 'Sale Orders',
    entityLabel: 'Sale Order',
    title: 'Sale Orders',
    description: 'Create and review sale orders for customers.',
    apiBase: `${API_ROOT}/sales/orders`,
    searchFields: ['so_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Sale Order',
    saveButtonLabel: 'Save Sale Order',
    emptyState: {
      title: 'No sale orders yet',
      description: 'Create a sale order to begin the sales workflow.',
    },
    renderType: 'sales',
    defaultTab: 'orders',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'SO Number A-Z', value: 'so_number-asc' },
      { label: 'SO Number Z-A', value: 'so_number-desc' },
    ],
  },
  'sales-invoices': {
    key: 'sales-invoices',
    group: 'Sales',
    label: 'Sales Invoices',
    entityLabel: 'Sales Invoice',
    title: 'Sales Invoices',
    description: 'Record invoices, shipments, and customer receipts.',
    apiBase: `${API_ROOT}/sales/invoices`,
    searchFields: ['invoice_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Sales Invoice',
    saveButtonLabel: 'Save Sales Invoice',
    emptyState: {
      title: 'No sales invoices yet',
      description: 'Create an invoice to ship inventory and bill a customer.',
    },
    renderType: 'sales',
    defaultTab: 'invoices',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Invoice Number A-Z', value: 'invoice_number-asc' },
      { label: 'Invoice Number Z-A', value: 'invoice_number-desc' },
    ],
  },
  'sales-returns': {
    key: 'sales-returns',
    group: 'Sales',
    label: 'Sales Returns',
    entityLabel: 'Sales Return',
    title: 'Sales Returns',
    description: 'Record customer returns and credit notes.',
    apiBase: `${API_ROOT}/sales/returns`,
    searchFields: ['return_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Return',
    saveButtonLabel: 'Save Return',
    emptyState: {
      title: 'No sales returns yet',
      description: 'Record a return when a customer sends goods back.',
    },
    renderType: 'sales',
    defaultTab: 'returns',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
    ],
  },
  'production-batches': {
    key: 'production-batches',
    group: 'Inventory',
    label: 'Production',
    entityLabel: 'Production Batch',
    title: 'Production Batches',
    description: 'Log production runs and track raw material usage.',
    apiBase: `${API_ROOT}/inventory/batches`,
    searchFields: ['batch_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Production Batch',
    saveButtonLabel: 'Save Production Batch',
    emptyState: { title: 'No production batches yet', description: 'Log a production run to get started.' },
    renderType: 'inventory',
    defaultTab: 'batches',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-transfers': {
    key: 'stock-transfers',
    group: 'Inventory',
    label: 'Stock Transfers',
    entityLabel: 'Stock Transfer',
    title: 'Stock Transfers',
    description: 'Move inventory between warehouses.',
    apiBase: `${API_ROOT}/inventory/transfers`,
    searchFields: ['transfer_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Stock Transfer',
    saveButtonLabel: 'Save Stock Transfer',
    emptyState: { title: 'No stock transfers yet', description: 'Create a transfer to move inventory between warehouses.' },
    renderType: 'inventory',
    defaultTab: 'transfers',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-adjustments': {
    key: 'stock-adjustments',
    group: 'Inventory',
    label: 'Stock Adjustments',
    entityLabel: 'Stock Adjustment',
    title: 'Stock Adjustments',
    description: 'Record damaged, missing, expired, or manually corrected stock.',
    apiBase: `${API_ROOT}/inventory/adjustments`,
    searchFields: ['adjustment_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Stock Adjustment',
    saveButtonLabel: 'Save Stock Adjustment',
    emptyState: { title: 'No stock adjustments yet', description: 'Record a discrepancy to get started.' },
    renderType: 'inventory',
    defaultTab: 'adjustments',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-count': {
    key: 'stock-count',
    group: 'Inventory',
    label: 'Stock Count',
    entityLabel: 'Stock Count',
    title: 'Stock Count',
    description: 'Compare physical counts to system stock and reconcile discrepancies.',
    apiBase: `${API_ROOT}/inventory/stock-levels`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'Stock Count',
    saveButtonLabel: 'Submit Count',
    emptyState: { title: '', description: '' },
    renderType: 'inventory',
    defaultTab: 'stock-count',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'income-expense-categories': {
    key: 'income-expense-categories',
    group: 'Finance',
    label: 'Income/Expense Categories',
    entityLabel: 'Category',
    title: 'Income/Expense Categories',
    description: 'Define the categories used when logging income and expense entries.',
    apiBase: `${API_ROOT}/finance/categories`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Category',
    saveButtonLabel: 'Save Category',
    emptyState: { title: 'No categories yet', description: 'Create income/expense categories to start logging entries.' },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Salary, Rental Income' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Income', value: 'income' },
          { label: 'Expense', value: 'expense' },
        ],
      },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'type', label: 'Type', sortable: true },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  'finance-entries': {
    key: 'finance-entries',
    group: 'Finance',
    label: 'Income & Expense',
    entityLabel: 'Entry',
    title: 'Income & Expense',
    description: 'Log non-sales income and operational expenses against an account.',
    apiBase: `${API_ROOT}/finance/entries`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Entry',
    saveButtonLabel: 'Save Entry',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'entries',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'finance-transfers': {
    key: 'finance-transfers',
    group: 'Finance',
    label: 'Fund Transfers',
    entityLabel: 'Fund Transfer',
    title: 'Fund Transfers',
    description: 'Move money between your own cash and bank accounts.',
    apiBase: `${API_ROOT}/finance/transfers`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Fund Transfer',
    saveButtonLabel: 'Save Fund Transfer',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'transfers',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'finance-ledger': {
    key: 'finance-ledger',
    group: 'Finance',
    label: 'Cash & Bank Book',
    entityLabel: 'Ledger',
    title: 'Cash & Bank Book',
    description: 'A running ledger of every transaction that touched an account.',
    apiBase: `${API_ROOT}/finance/account-ledger`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'ledger',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  delivery: {
    key: 'delivery',
    group: 'Sales',
    label: 'Delivery',
    entityLabel: 'Delivery',
    title: 'Delivery',
    description: 'Schedule deliveries and track vehicle, driver, and status.',
    apiBase: `${API_ROOT}/deliveries`,
    searchFields: ['delivery_number'],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Delivery',
    saveButtonLabel: 'Save Delivery',
    emptyState: { title: '', description: '' },
    renderType: 'delivery',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-current-stock': {
    key: 'report-current-stock',
    group: 'Reports',
    label: 'Current Stock',
    entityLabel: 'Report',
    title: 'Current Stock',
    description: 'Live stock quantity by product and warehouse.',
    apiBase: `${API_ROOT}/reports/current-stock`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'current-stock',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-low-stock': {
    key: 'report-low-stock',
    group: 'Reports',
    label: 'Low Stock',
    entityLabel: 'Report',
    title: 'Low Stock',
    description: 'Products at or below their minimum stock level.',
    apiBase: `${API_ROOT}/reports/low-stock`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'low-stock',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-stock-movement': {
    key: 'report-stock-movement',
    group: 'Reports',
    label: 'Stock Movement',
    entityLabel: 'Report',
    title: 'Stock Movement',
    description: 'Every stock transaction across the system.',
    apiBase: `${API_ROOT}/reports/stock-movement`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'stock-movement',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-stock-ledger': {
    key: 'report-stock-ledger',
    group: 'Reports',
    label: 'Stock Ledger',
    entityLabel: 'Report',
    title: 'Stock Ledger',
    description: 'Running balance for one product at one warehouse.',
    apiBase: `${API_ROOT}/stock-ledger/ledger`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'stock-ledger',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-purchase-summary': {
    key: 'report-purchase-summary',
    group: 'Reports',
    label: 'Purchase Summary',
    entityLabel: 'Report',
    title: 'Purchase Summary',
    description: 'Purchases by supplier for a date range.',
    apiBase: `${API_ROOT}/reports/purchase-summary`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'purchase-summary',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-production-summary': {
    key: 'report-production-summary',
    group: 'Reports',
    label: 'Production Summary',
    entityLabel: 'Report',
    title: 'Production Summary',
    description: 'Production batches and output by day or month.',
    apiBase: `${API_ROOT}/reports/production-summary`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'production-summary',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-sales-summary': {
    key: 'report-sales-summary',
    group: 'Reports',
    label: 'Sales Summary',
    entityLabel: 'Report',
    title: 'Sales Summary',
    description: 'Sales broken down by product and by customer.',
    apiBase: `${API_ROOT}/reports/sales-summary`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'sales-summary',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-outstanding': {
    key: 'report-outstanding',
    group: 'Reports',
    label: 'Outstanding Balances',
    entityLabel: 'Report',
    title: 'Customer/Supplier Outstanding',
    description: 'Who owes you, and who you owe.',
    apiBase: `${API_ROOT}/reports/outstanding`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'outstanding',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-profit-loss': {
    key: 'report-profit-loss',
    group: 'Reports',
    label: 'Profit & Loss',
    entityLabel: 'Report',
    title: 'Profit & Loss',
    description: 'Revenue, cost of goods sold, and net profit for a date range.',
    apiBase: `${API_ROOT}/reports/profit-loss`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'profit-loss',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-tax-summary': {
    key: 'report-tax-summary',
    group: 'Reports',
    label: 'Tax / VAT Summary',
    entityLabel: 'Report',
    title: 'Tax / VAT Summary',
    description: 'Tax collected on sales vs. tax paid on purchases, by month.',
    apiBase: `${API_ROOT}/reports/tax-summary`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'tax-summary',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-expense': {
    key: 'report-expense',
    group: 'Reports',
    label: 'Income & Expense',
    entityLabel: 'Report',
    title: 'Income & Expense',
    description: 'Every income/expense entry, filterable by type and category.',
    apiBase: `${API_ROOT}/reports/expense-report`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'expense-report',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-customer-statement': {
    key: 'report-customer-statement',
    group: 'Reports',
    label: 'Customer Statement',
    entityLabel: 'Report',
    title: 'Customer Statement of Account',
    description: "A running ledger of one customer's invoices and payments.",
    apiBase: `${API_ROOT}/reports/customer-statement`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'customer-statement',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-supplier-statement': {
    key: 'report-supplier-statement',
    group: 'Reports',
    label: 'Supplier Statement',
    entityLabel: 'Report',
    title: 'Supplier Statement of Account',
    description: "A running ledger of one supplier's vouchers and payments.",
    apiBase: `${API_ROOT}/reports/supplier-statement`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'supplier-statement',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-sales-backlog': {
    key: 'report-sales-backlog',
    group: 'Reports',
    label: 'Sales Order Backlog',
    entityLabel: 'Report',
    title: 'Sales Order Backlog',
    description: 'Open sales orders not yet delivered or cancelled.',
    apiBase: `${API_ROOT}/reports/sales-backlog`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'sales-backlog',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-open-purchase-orders': {
    key: 'report-open-purchase-orders',
    group: 'Reports',
    label: 'Open Purchase Orders',
    entityLabel: 'Report',
    title: 'Open Purchase Orders',
    description: 'Open purchase orders not yet received or cancelled.',
    apiBase: `${API_ROOT}/reports/open-purchase-orders`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'open-purchase-orders',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-inventory-valuation': {
    key: 'report-inventory-valuation',
    group: 'Reports',
    label: 'Inventory Valuation',
    entityLabel: 'Report',
    title: 'Inventory Valuation',
    description: 'Stock value rolled up by category and by warehouse.',
    apiBase: `${API_ROOT}/reports/inventory-valuation`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'inventory-valuation',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-slow-moving-stock': {
    key: 'report-slow-moving-stock',
    group: 'Reports',
    label: 'Slow-Moving Stock',
    entityLabel: 'Report',
    title: 'Slow-Moving / Dead Stock',
    description: 'Stock on hand with no movement in a configurable window.',
    apiBase: `${API_ROOT}/reports/slow-moving-stock`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'slow-moving-stock',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-abc-analysis': {
    key: 'report-abc-analysis',
    group: 'Reports',
    label: 'ABC Analysis',
    entityLabel: 'Report',
    title: 'ABC Analysis',
    description: 'Products ranked and classified by revenue contribution.',
    apiBase: `${API_ROOT}/reports/abc-analysis`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'abc-analysis',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-stock-transfer-register': {
    key: 'report-stock-transfer-register',
    group: 'Reports',
    label: 'Stock Transfer Register',
    entityLabel: 'Report',
    title: 'Stock Transfer Register',
    description: 'Transfers between warehouses, valued.',
    apiBase: `${API_ROOT}/reports/stock-transfer-register`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'stock-transfer-register',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-stock-adjustment': {
    key: 'report-stock-adjustment',
    group: 'Reports',
    label: 'Stock Adjustments',
    entityLabel: 'Report',
    title: 'Stock Adjustment / Write-off',
    description: 'Damaged, missing, expired, and manual stock adjustments, valued.',
    apiBase: `${API_ROOT}/reports/stock-adjustment-report`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'stock-adjustment-report',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-po-variance': {
    key: 'report-po-variance',
    group: 'Reports',
    label: 'PO Variance',
    entityLabel: 'Report',
    title: 'PO vs. Voucher Variance',
    description: 'What was ordered vs. what the supplier actually invoiced.',
    apiBase: `${API_ROOT}/reports/po-variance`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'po-variance',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-supplier-price-trend': {
    key: 'report-supplier-price-trend',
    group: 'Reports',
    label: 'Supplier Price Trend',
    entityLabel: 'Report',
    title: 'Supplier Price Trend',
    description: "One product's purchase price across every voucher over time.",
    apiBase: `${API_ROOT}/reports/supplier-price-trend`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'supplier-price-trend',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-cash-flow': {
    key: 'report-cash-flow',
    group: 'Reports',
    label: 'Cash Flow Statement',
    entityLabel: 'Report',
    title: 'Cash Flow Statement',
    description: 'Cash in vs. cash out by month, on a cash basis.',
    apiBase: `${API_ROOT}/reports/cash-flow`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'cash-flow',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-fund-transfer-register': {
    key: 'report-fund-transfer-register',
    group: 'Reports',
    label: 'Fund Transfer Register',
    entityLabel: 'Report',
    title: 'Fund Transfer Register',
    description: 'Deposits, withdrawals, and transfers between accounts.',
    apiBase: `${API_ROOT}/reports/fund-transfer-register`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'fund-transfer-register',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-delivery-performance': {
    key: 'report-delivery-performance',
    group: 'Reports',
    label: 'Delivery Performance',
    entityLabel: 'Report',
    title: 'Delivery Performance',
    description: 'On-time vs. failed delivery rate.',
    apiBase: `${API_ROOT}/reports/delivery-performance`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'delivery-performance',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-document-register': {
    key: 'report-document-register',
    group: 'Reports',
    label: 'Document Register',
    entityLabel: 'Report',
    title: 'Document Register',
    description: 'A single index across every PO, voucher, order, and invoice.',
    apiBase: `${API_ROOT}/reports/document-register`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'document-register',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-salesperson-performance': {
    key: 'report-salesperson-performance',
    group: 'Reports',
    label: 'Salesperson Performance',
    entityLabel: 'Report',
    title: 'Salesperson Performance',
    description: 'Revenue and invoice count by sales rep.',
    apiBase: `${API_ROOT}/reports/salesperson-performance`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'salesperson-performance',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-supplier-scorecard': {
    key: 'report-supplier-scorecard',
    group: 'Reports',
    label: 'Supplier Scorecard',
    entityLabel: 'Report',
    title: 'Supplier Performance Scorecard',
    description: 'On-time delivery rate and quality mix by supplier.',
    apiBase: `${API_ROOT}/reports/supplier-scorecard`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'supplier-scorecard',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-expiry': {
    key: 'report-expiry',
    group: 'Reports',
    label: 'Expiry Report',
    entityLabel: 'Report',
    title: 'Expiry Report',
    description: 'Batches received or produced with an expiry date, nearest first.',
    apiBase: `${API_ROOT}/reports/expiry-report`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'expiry-report',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-sales-returns': {
    key: 'report-sales-returns',
    group: 'Reports',
    label: 'Sales Returns',
    entityLabel: 'Report',
    title: 'Sales Returns',
    description: 'Every credit note in the period, by customer.',
    apiBase: `${API_ROOT}/reports/sales-returns`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'sales-returns-report',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-purchase-returns': {
    key: 'report-purchase-returns',
    group: 'Reports',
    label: 'Purchase Returns',
    entityLabel: 'Report',
    title: 'Purchase Returns',
    description: 'Every debit note in the period, by supplier.',
    apiBase: `${API_ROOT}/reports/purchase-returns`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'purchase-returns-report',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-chart-of-accounts': {
    key: 'report-chart-of-accounts',
    group: 'Reports',
    label: 'Chart of Accounts',
    entityLabel: 'Report',
    title: 'Chart of Accounts',
    description: 'Every General Ledger account and its current balance.',
    apiBase: `${API_ROOT}/reports/chart-of-accounts`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'chart-of-accounts',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-trial-balance': {
    key: 'report-trial-balance',
    group: 'Reports',
    label: 'Trial Balance',
    entityLabel: 'Report',
    title: 'Trial Balance',
    description: 'Every account with activity, net balance, as of a date.',
    apiBase: `${API_ROOT}/reports/trial-balance`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'trial-balance',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-balance-sheet': {
    key: 'report-balance-sheet',
    group: 'Reports',
    label: 'Balance Sheet',
    entityLabel: 'Report',
    title: 'Balance Sheet',
    description: 'Assets, liabilities, and equity as of a date.',
    apiBase: `${API_ROOT}/reports/balance-sheet`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'balance-sheet',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'report-journal-register': {
    key: 'report-journal-register',
    group: 'Reports',
    label: 'Journal Register',
    entityLabel: 'Report',
    title: 'Journal Register',
    description: 'Every General Ledger entry posted in a date range.',
    apiBase: `${API_ROOT}/reports/journal-register`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'reports',
    defaultTab: 'journal-register',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  users: {
    key: 'users',
    group: 'Access Control',
    label: 'Users',
    entityLabel: 'User',
    title: 'Users',
    description: 'People who can log into the system, and the role each one has.',
    apiBase: `${API_ROOT}/user-management/users`,
    searchFields: ['username', 'full_name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New User',
    saveButtonLabel: 'Save User',
    emptyState: {
      title: 'No users yet',
      description: 'Create a user account to give someone access to the system.',
    },
    lookups: [
      { key: 'roles', apiBase: `${API_ROOT}/user-management/roles`, valueKey: 'id', labelKey: 'name' },
    ],
    fields: [
      { key: 'username', label: 'Username', type: 'text', required: true, placeholder: 'Login username' },
      {
        key: 'password',
        label: 'Password',
        type: 'password',
        requiredOnCreate: true,
        placeholder: 'Required',
        editPlaceholder: 'Leave blank to keep current password',
      },
      { key: 'full_name', label: 'Full Name', type: 'text', placeholder: 'Optional full name' },
      { key: 'role_id', label: 'Role', type: 'select', required: true, placeholder: 'Select a role', lookupKey: 'roles', valueType: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'active',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
          { label: 'Suspended', value: 'suspended' },
        ],
      },
      {
        key: 'timezone',
        label: 'Timezone',
        type: 'select',
        defaultValue: 'UTC',
        placeholder: 'UTC',
        options: timezoneOptions,
      },
    ],
    columns: [
      { key: 'username', label: 'Username', sortable: true },
      { key: 'full_name', label: 'Full Name', sortable: true },
      { key: 'role_name', label: 'Role' },
      { key: 'status', label: 'Status', sortable: true },
      { key: 'timezone', label: 'Timezone', sortable: true },
      { key: 'last_login', label: 'Last Login' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Username A-Z', value: 'username-asc' },
      { label: 'Username Z-A', value: 'username-desc' },
    ],
  },
  roles: {
    key: 'roles',
    group: 'Access Control',
    label: 'Roles',
    entityLabel: 'Role',
    title: 'Roles',
    description: 'Define the access profiles used across the application.',
    apiBase: `${API_ROOT}/user-management/roles`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Role',
    saveButtonLabel: 'Save Role',
    emptyState: {
      title: 'No roles yet',
      description: 'Create roles to group permissions for users.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Role name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
    actions: ['assign-permissions'],
  },
  permissions: {
    key: 'permissions',
    group: 'Access Control',
    label: 'Permissions',
    entityLabel: 'Permission',
    title: 'Permissions',
    description: 'The fixed set of permissions available to assign to roles. View-only - add capabilities in code, not here.',
    apiBase: `${API_ROOT}/user-management/permissions`,
    searchFields: ['name', 'module'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    // No create/edit/delete for permissions - they're a fixed catalog tied to
    // what the backend actually enforces, not user-editable data. Roles are
    // still assigned a subset of these via the "Assign Permissions" dialog.
    readOnly: true,
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: {
      title: 'No permissions yet',
      description: '',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Permission name' },
      { key: 'module', label: 'Module', type: 'text', placeholder: 'Module name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'module', label: 'Module', sortable: true },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Module A-Z', value: 'module-asc' },
      { label: 'Module Z-A', value: 'module-desc' },
    ],
  },
  'audit-log': {
    key: 'audit-log',
    group: 'Access Control',
    label: 'Audit Log',
    entityLabel: 'Audit Log',
    title: 'Audit Log',
    description: 'Every logged action across the system, with who did it and when.',
    apiBase: `${API_ROOT}/audit`,
    searchFields: [],
    defaultSort: { sortBy: 'timestamp', order: 'DESC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'audit',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'print-page-setups': {
    key: 'print-page-setups',
    group: 'Access Control',
    label: 'Print Page Setups',
    entityLabel: 'Print Page Setup',
    title: 'Print Page Setups',
    description: 'Named page size/margin profiles used when printing documents. Mark one as default; pick a different one at print time whenever you need to.',
    apiBase: `${API_ROOT}/master/print-page-setups`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'name', order: 'ASC' },
    createButtonLabel: 'New Print Page Setup',
    saveButtonLabel: 'Save Print Page Setup',
    emptyState: {
      title: 'No print page setups yet',
      description: 'Create one to control the page size and margins used when printing documents.',
    },
    actions: ['set-default'],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. A4, Thermal Receipt, Letter' },
      { key: 'page_width', label: 'Page Width (mm)', type: 'number', step: '0.01', defaultValue: 210 },
      { key: 'page_height', label: 'Page Height (mm)', type: 'number', step: '0.01', defaultValue: 297 },
      { key: 'margin_top', label: 'Margin Top (mm)', type: 'number', step: '0.01', defaultValue: 15 },
      { key: 'margin_bottom', label: 'Margin Bottom (mm)', type: 'number', step: '0.01', defaultValue: 15 },
      { key: 'margin_left', label: 'Margin Left (mm)', type: 'number', step: '0.01', defaultValue: 10 },
      { key: 'margin_right', label: 'Margin Right (mm)', type: 'number', step: '0.01', defaultValue: 10 },
      { key: 'is_default', label: 'Default Setup', type: 'checkbox' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'page_width', label: 'Width (mm)', align: 'right' },
      { key: 'page_height', label: 'Height (mm)', align: 'right' },
      { key: 'is_default', label: 'Default', sortable: true },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Newest first', value: 'id-desc' },
    ],
  },
};

export const MASTER_DATA_SECTION_ORDER = ['Overview', 'Master Data', 'Procurement', 'Sales', 'Inventory', 'Finance', 'Reports', 'Access Control'];

export const MASTER_DATA_MODULE_ORDER = [
  'dashboard',
  'categories',
  'products',
  'pricing-tiers',
  'suppliers',
  'customers',
  'warehouses',
  'accounts',
  'payment-methods',
  'purchase-orders',
  'purchase-vouchers',
  'purchase-returns',
  'sale-orders',
  'sales-invoices',
  'sales-returns',
  'delivery',
  'production-batches',
  'stock-transfers',
  'stock-adjustments',
  'stock-count',
  'income-expense-categories',
  'finance-entries',
  'finance-transfers',
  'finance-ledger',
  'report-current-stock',
  'report-low-stock',
  'report-stock-movement',
  'report-stock-ledger',
  'report-purchase-summary',
  'report-production-summary',
  'report-sales-summary',
  'report-sales-by-category',
  'report-payment-method-analysis',
  'report-outstanding',
  'report-profit-loss',
  'report-tax-summary',
  'report-expense',
  'report-customer-statement',
  'report-supplier-statement',
  'report-sales-backlog',
  'report-open-purchase-orders',
  'report-inventory-valuation',
  'report-slow-moving-stock',
  'report-abc-analysis',
  'report-stock-transfer-register',
  'report-stock-adjustment',
  'report-po-variance',
  'report-supplier-price-trend',
  'report-cash-flow',
  'report-fund-transfer-register',
  'report-delivery-performance',
  'report-document-register',
  'report-salesperson-performance',
  'report-supplier-scorecard',
  'report-expiry',
  'report-sales-returns',
  'report-purchase-returns',
  'report-chart-of-accounts',
  'report-trial-balance',
  'report-balance-sheet',
  'report-journal-register',
  'users',
  'roles',
  'permissions',
  'audit-log',
  'print-page-setups',
];

export const MODULE_LOOKUP_MAP = MASTER_DATA_MODULE_ORDER.reduce((accumulator, key) => {
  accumulator[key] = MASTER_DATA_MODULES[key];
  return accumulator;
}, {});
