const API_ROOT = 'http://localhost:5000/api';

const moneyField = {
  step: '0.01',
};

export const MASTER_DATA_MODULES = {
  categories: {
    key: 'categories',
    group: 'Master Data',
    label: 'Categories',
    entityLabel: 'Category',
    title: 'Categories',
    description: 'Organize the master catalog used across products and finance.',
    apiBase: `${API_ROOT}/master/categories`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Category',
    saveButtonLabel: 'Save Category',
    emptyState: {
      title: 'No categories yet',
      description: 'Create the first category to start structuring your catalog.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Category name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'id', label: 'ID', sortable: true, width: '84px' },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  products: {
    key: 'products',
    group: 'Master Data',
    label: 'Products',
    entityLabel: 'Product',
    title: 'Products',
    description: 'Maintain product master records used by procurement, sales, and inventory.',
    apiBase: `${API_ROOT}/master/products`,
    searchFields: ['name', 'product_code', 'barcode'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Product',
    saveButtonLabel: 'Save Product',
    emptyState: {
      title: 'No products yet',
      description: 'Create a product to start managing stock and pricing.',
    },
    lookups: [
      {
        key: 'categories',
        apiBase: `${API_ROOT}/master/categories`,
        valueKey: 'id',
        labelKey: 'name',
      },
      {
        key: 'productTypes',
        apiBase: `${API_ROOT}/master/product-types`,
        valueKey: 'id',
        labelKey: 'name',
      },
    ],
    fields: [
      { key: 'product_code', label: 'Product Code', type: 'text', placeholder: 'Optional product code' },
      { key: 'barcode', label: 'Barcode', type: 'text', placeholder: 'Optional barcode' },
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Product name' },
      {
        key: 'category_id',
        label: 'Category',
        type: 'select',
        placeholder: 'Select a category',
        lookupKey: 'categories',
        valueType: 'number',
      },
      { key: 'group_name', label: 'Group', type: 'text', placeholder: 'Optional group name' },
      { key: 'unit', label: 'Unit', type: 'text', placeholder: 'Optional unit' },
      { key: 'contains', label: 'Contains', type: 'textarea', placeholder: 'Optional ingredients or packaging note' },
      { key: 'min_stock_level', label: 'Minimum Stock', type: 'number', ...moneyField, placeholder: '0.00' },
      {
        key: 'product_type_id',
        label: 'Product Type',
        type: 'select',
        required: true,
        placeholder: 'Select a product type',
        lookupKey: 'productTypes',
        valueType: 'number',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
        ],
      },
    ],
    // Pricing is set separately from creation (see the "Set Price" row action) -
    // cost/markup/selling price live in their own dialog, not the create/edit form.
    pricingFields: [
      { key: 'cost_price', label: 'Cost Price', type: 'number', ...moneyField, placeholder: '0.00' },
      {
        key: 'markup_type',
        label: 'Markup Type',
        type: 'select',
        options: [
          { label: 'Fixed', value: 'fixed' },
          { label: 'Percentage', value: 'percentage' },
        ],
      },
      { key: 'markup_value', label: 'Markup Value', type: 'number', ...moneyField, placeholder: '0.00' },
    ],
    actions: ['set-price'],
    // Enables row checkboxes + the "Set Price for N selected" bulk action.
    bulkPricing: true,
    columns: [
      { key: 'product_code', label: 'Code', sortable: true },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'category_id', label: 'Category' },
      { key: 'product_type_id', label: 'Product Type' },
      { key: 'selling_price', label: 'Price', align: 'right' },
      { key: 'status', label: 'Status', sortable: true },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Code A-Z', value: 'product_code-asc' },
      { label: 'Code Z-A', value: 'product_code-desc' },
      { label: 'Price low-high', value: 'selling_price-asc' },
      { label: 'Price high-low', value: 'selling_price-desc' },
    ],
  },
  'product-types': {
    key: 'product-types',
    group: 'Master Data',
    label: 'Product Types',
    entityLabel: 'Product Type',
    title: 'Product Types',
    description: 'Manage product type categories used by the product master data.',
    apiBase: `${API_ROOT}/master/product-types`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Product Type',
    saveButtonLabel: 'Save Product Type',
    emptyState: {
      title: 'No product types yet',
      description: 'Create a product type to organize your catalog.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Product type name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  suppliers: {
    key: 'suppliers',
    group: 'Master Data',
    label: 'Suppliers',
    entityLabel: 'Supplier',
    title: 'Suppliers',
    description: 'Track supplier records and contact details used by procurement.',
    apiBase: `${API_ROOT}/master/suppliers`,
    searchFields: ['name', 'contact_person', 'phone', 'email'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Supplier',
    saveButtonLabel: 'Save Supplier',
    emptyState: {
      title: 'No suppliers yet',
      description: 'Add a supplier to begin managing procurement records.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Supplier name' },
      { key: 'contact_person', label: 'Contact Person', type: 'text', placeholder: 'Optional contact person' },
      { key: 'phone', label: 'Phone', type: 'text', placeholder: 'Optional phone number' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'Optional email address' },
      { key: 'address', label: 'Address', type: 'textarea', placeholder: 'Optional address' },
      { key: 'outstanding_balance', label: 'Outstanding Balance', type: 'number', ...moneyField, placeholder: '0.00' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'contact_person', label: 'Contact Person' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'outstanding_balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'outstanding_balance-asc' },
      { label: 'Balance high-low', value: 'outstanding_balance-desc' },
    ],
  },
  customers: {
    key: 'customers',
    group: 'Master Data',
    label: 'Customers',
    entityLabel: 'Customer',
    title: 'Customers',
    description: 'Maintain customer records used by sales and accounts receivable.',
    apiBase: `${API_ROOT}/master/customers`,
    searchFields: ['name', 'contact_person', 'phone', 'email', 'customer_type'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Customer',
    saveButtonLabel: 'Save Customer',
    emptyState: {
      title: 'No customers yet',
      description: 'Create a customer to start managing sales accounts.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Customer name' },
      { key: 'customer_type', label: 'Customer Type', type: 'text', placeholder: 'Retail, wholesale, distributor...' },
      { key: 'contact_person', label: 'Contact Person', type: 'text', placeholder: 'Optional contact person' },
      { key: 'phone', label: 'Phone', type: 'text', placeholder: 'Optional phone number' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'Optional email address' },
      { key: 'address', label: 'Address', type: 'textarea', placeholder: 'Optional address' },
      { key: 'credit_limit', label: 'Credit Limit', type: 'number', ...moneyField, placeholder: '0.00' },
      { key: 'outstanding_balance', label: 'Outstanding Balance', type: 'number', ...moneyField, placeholder: '0.00' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'customer_type', label: 'Type' },
      { key: 'contact_person', label: 'Contact Person' },
      { key: 'phone', label: 'Phone' },
      { key: 'outstanding_balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'outstanding_balance-asc' },
      { label: 'Balance high-low', value: 'outstanding_balance-desc' },
    ],
  },
  warehouses: {
    key: 'warehouses',
    group: 'Master Data',
    label: 'Warehouses',
    entityLabel: 'Warehouse',
    title: 'Warehouses',
    description: 'Manage warehouse locations and fulfillment destinations.',
    apiBase: `${API_ROOT}/master/warehouses`,
    searchFields: ['name', 'location', 'warehouse_type'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Warehouse',
    saveButtonLabel: 'Save Warehouse',
    emptyState: {
      title: 'No warehouses yet',
      description: 'Create a warehouse to organize inventory locations.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Warehouse name' },
      { key: 'location', label: 'Location', type: 'text', placeholder: 'Optional location' },
      { key: 'warehouse_type', label: 'Warehouse Type', type: 'text', placeholder: 'Raw material, finished goods...' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'location', label: 'Location' },
      { key: 'warehouse_type', label: 'Type' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  accounts: {
    key: 'accounts',
    group: 'Master Data',
    label: 'Accounts',
    entityLabel: 'Account',
    title: 'Accounts',
    description: 'Maintain cash and bank accounts used by finance and payments.',
    apiBase: `${API_ROOT}/master/accounts`,
    searchFields: ['name', 'bank_name', 'account_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Account',
    saveButtonLabel: 'Save Account',
    emptyState: {
      title: 'No accounts yet',
      description: 'Add a finance account to track balances and transactions.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Account name' },
      { key: 'account_type', label: 'Account Type', type: 'text', placeholder: 'Cash or bank' },
      { key: 'account_number', label: 'Account Number', type: 'text', placeholder: 'Optional account number' },
      { key: 'bank_name', label: 'Bank Name', type: 'text', placeholder: 'Optional bank name' },
      { key: 'balance', label: 'Balance', type: 'number', ...moneyField, placeholder: '0.00' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'account_type', label: 'Type' },
      { key: 'account_number', label: 'Account Number' },
      { key: 'bank_name', label: 'Bank' },
      { key: 'balance', label: 'Balance', align: 'right' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Balance low-high', value: 'balance-asc' },
      { label: 'Balance high-low', value: 'balance-desc' },
      { label: 'Bank A-Z', value: 'bank_name-asc' },
      { label: 'Bank Z-A', value: 'bank_name-desc' },
    ],
  },
  'payment-methods': {
    key: 'payment-methods',
    group: 'Master Data',
    label: 'Payment Methods',
    entityLabel: 'Payment Method',
    title: 'Payment Methods',
    description: 'Manage the payment channels available in the system.',
    apiBase: `${API_ROOT}/master/payment-methods`,
    searchFields: ['name', 'code', 'description'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Payment Method',
    saveButtonLabel: 'Save Payment Method',
    emptyState: {
      title: 'No payment methods yet',
      description: 'Create the first payment method used by the organization.',
    },
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true, placeholder: 'Payment code' },
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Payment method name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
      { key: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { key: 'code', label: 'Code', sortable: true },
      { key: 'name', label: 'Name', sortable: true },
      { key: 'is_active', label: 'Status' },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Code A-Z', value: 'code-asc' },
      { label: 'Code Z-A', value: 'code-desc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  'purchase-orders': {
    key: 'purchase-orders',
    group: 'Procurement',
    label: 'Purchase Orders',
    entityLabel: 'Purchase Order',
    title: 'Purchase Orders',
    description: 'Create and review purchase orders for suppliers.',
    apiBase: `${API_ROOT}/procurement/orders`,
    searchFields: ['po_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Purchase Order',
    saveButtonLabel: 'Save Purchase Order',
    emptyState: {
      title: 'No purchase orders yet',
      description: 'Create a purchase order to begin procurement workflows.',
    },
    renderType: 'procurement',
    defaultTab: 'orders',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'PO Number A-Z', value: 'po_number-asc' },
      { label: 'PO Number Z-A', value: 'po_number-desc' },
    ],
  },
  'purchase-vouchers': {
    key: 'purchase-vouchers',
    group: 'Procurement',
    label: 'Purchase Vouchers',
    entityLabel: 'Purchase Voucher',
    title: 'Purchase Vouchers',
    description: 'Record receipts and voucher details for received goods.',
    apiBase: `${API_ROOT}/procurement/vouchers`,
    searchFields: ['voucher_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Purchase Voucher',
    saveButtonLabel: 'Save Purchase Voucher',
    emptyState: {
      title: 'No purchase vouchers yet',
      description: 'Create a voucher to track receipts and payments.',
    },
    renderType: 'procurement',
    defaultTab: 'vouchers',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Voucher Number A-Z', value: 'voucher_number-asc' },
      { label: 'Voucher Number Z-A', value: 'voucher_number-desc' },
    ],
  },
  'sale-orders': {
    key: 'sale-orders',
    group: 'Sales',
    label: 'Sale Orders',
    entityLabel: 'Sale Order',
    title: 'Sale Orders',
    description: 'Create and review sale orders for customers.',
    apiBase: `${API_ROOT}/sales/orders`,
    searchFields: ['so_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Sale Order',
    saveButtonLabel: 'Save Sale Order',
    emptyState: {
      title: 'No sale orders yet',
      description: 'Create a sale order to begin the sales workflow.',
    },
    renderType: 'sales',
    defaultTab: 'orders',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'SO Number A-Z', value: 'so_number-asc' },
      { label: 'SO Number Z-A', value: 'so_number-desc' },
    ],
  },
  'sales-invoices': {
    key: 'sales-invoices',
    group: 'Sales',
    label: 'Sales Invoices',
    entityLabel: 'Sales Invoice',
    title: 'Sales Invoices',
    description: 'Record invoices, shipments, and customer receipts.',
    apiBase: `${API_ROOT}/sales/invoices`,
    searchFields: ['invoice_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Sales Invoice',
    saveButtonLabel: 'Save Sales Invoice',
    emptyState: {
      title: 'No sales invoices yet',
      description: 'Create an invoice to ship inventory and bill a customer.',
    },
    renderType: 'sales',
    defaultTab: 'invoices',
    fields: [],
    columns: [],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Invoice Number A-Z', value: 'invoice_number-asc' },
      { label: 'Invoice Number Z-A', value: 'invoice_number-desc' },
    ],
  },
  'production-batches': {
    key: 'production-batches',
    group: 'Inventory',
    label: 'Production',
    entityLabel: 'Production Batch',
    title: 'Production Batches',
    description: 'Log production runs and track raw material usage.',
    apiBase: `${API_ROOT}/inventory/batches`,
    searchFields: ['batch_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Production Batch',
    saveButtonLabel: 'Save Production Batch',
    emptyState: { title: 'No production batches yet', description: 'Log a production run to get started.' },
    renderType: 'inventory',
    defaultTab: 'batches',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-transfers': {
    key: 'stock-transfers',
    group: 'Inventory',
    label: 'Stock Transfers',
    entityLabel: 'Stock Transfer',
    title: 'Stock Transfers',
    description: 'Move inventory between warehouses.',
    apiBase: `${API_ROOT}/inventory/transfers`,
    searchFields: ['transfer_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Stock Transfer',
    saveButtonLabel: 'Save Stock Transfer',
    emptyState: { title: 'No stock transfers yet', description: 'Create a transfer to move inventory between warehouses.' },
    renderType: 'inventory',
    defaultTab: 'transfers',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-adjustments': {
    key: 'stock-adjustments',
    group: 'Inventory',
    label: 'Stock Adjustments',
    entityLabel: 'Stock Adjustment',
    title: 'Stock Adjustments',
    description: 'Record damaged, missing, expired, or manually corrected stock.',
    apiBase: `${API_ROOT}/inventory/adjustments`,
    searchFields: ['adjustment_number'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Stock Adjustment',
    saveButtonLabel: 'Save Stock Adjustment',
    emptyState: { title: 'No stock adjustments yet', description: 'Record a discrepancy to get started.' },
    renderType: 'inventory',
    defaultTab: 'adjustments',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'stock-count': {
    key: 'stock-count',
    group: 'Inventory',
    label: 'Stock Count',
    entityLabel: 'Stock Count',
    title: 'Stock Count',
    description: 'Compare physical counts to system stock and reconcile discrepancies.',
    apiBase: `${API_ROOT}/inventory/stock-levels`,
    searchFields: [],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'Stock Count',
    saveButtonLabel: 'Submit Count',
    emptyState: { title: '', description: '' },
    renderType: 'inventory',
    defaultTab: 'stock-count',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'income-expense-categories': {
    key: 'income-expense-categories',
    group: 'Finance',
    label: 'Income/Expense Categories',
    entityLabel: 'Category',
    title: 'Income/Expense Categories',
    description: 'Define the categories used when logging income and expense entries.',
    apiBase: `${API_ROOT}/finance/categories`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Category',
    saveButtonLabel: 'Save Category',
    emptyState: { title: 'No categories yet', description: 'Create income/expense categories to start logging entries.' },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Salary, Rental Income' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Income', value: 'income' },
          { label: 'Expense', value: 'expense' },
        ],
      },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'type', label: 'Type', sortable: true },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
  },
  'finance-entries': {
    key: 'finance-entries',
    group: 'Finance',
    label: 'Income & Expense',
    entityLabel: 'Entry',
    title: 'Income & Expense',
    description: 'Log non-sales income and operational expenses against an account.',
    apiBase: `${API_ROOT}/finance/entries`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Entry',
    saveButtonLabel: 'Save Entry',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'entries',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'finance-transfers': {
    key: 'finance-transfers',
    group: 'Finance',
    label: 'Fund Transfers',
    entityLabel: 'Fund Transfer',
    title: 'Fund Transfers',
    description: 'Move money between your own cash and bank accounts.',
    apiBase: `${API_ROOT}/finance/transfers`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Fund Transfer',
    saveButtonLabel: 'Save Fund Transfer',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'transfers',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  'finance-ledger': {
    key: 'finance-ledger',
    group: 'Finance',
    label: 'Cash & Bank Book',
    entityLabel: 'Ledger',
    title: 'Cash & Bank Book',
    description: 'A running ledger of every transaction that touched an account.',
    apiBase: `${API_ROOT}/finance/account-ledger`,
    searchFields: [],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'finance',
    defaultTab: 'ledger',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  delivery: {
    key: 'delivery',
    group: 'Sales',
    label: 'Delivery',
    entityLabel: 'Delivery',
    title: 'Delivery',
    description: 'Schedule deliveries and track vehicle, driver, and status.',
    apiBase: `${API_ROOT}/deliveries`,
    searchFields: ['delivery_number'],
    defaultSort: { sortBy: 'date', order: 'DESC' },
    createButtonLabel: 'New Delivery',
    saveButtonLabel: 'Save Delivery',
    emptyState: { title: '', description: '' },
    renderType: 'delivery',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  roles: {
    key: 'roles',
    group: 'Access Control',
    label: 'Roles',
    entityLabel: 'Role',
    title: 'Roles',
    description: 'Define the access profiles used across the application.',
    apiBase: `${API_ROOT}/user-management/roles`,
    searchFields: ['name'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Role',
    saveButtonLabel: 'Save Role',
    emptyState: {
      title: 'No roles yet',
      description: 'Create roles to group permissions for users.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Role name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
    ],
    actions: ['assign-permissions'],
  },
  permissions: {
    key: 'permissions',
    group: 'Access Control',
    label: 'Permissions',
    entityLabel: 'Permission',
    title: 'Permissions',
    description: 'Maintain permission definitions and module assignments.',
    apiBase: `${API_ROOT}/user-management/permissions`,
    searchFields: ['name', 'module'],
    defaultSort: { sortBy: 'id', order: 'DESC' },
    createButtonLabel: 'New Permission',
    saveButtonLabel: 'Save Permission',
    emptyState: {
      title: 'No permissions yet',
      description: 'Add a permission to expose a capability in the system.',
    },
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Permission name' },
      { key: 'module', label: 'Module', type: 'text', placeholder: 'Module name' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
    ],
    columns: [
      { key: 'name', label: 'Name', sortable: true },
      { key: 'module', label: 'Module', sortable: true },
      { key: 'description', label: 'Description' },
    ],
    sortOptions: [
      { label: 'Newest first', value: 'id-desc' },
      { label: 'Oldest first', value: 'id-asc' },
      { label: 'Name A-Z', value: 'name-asc' },
      { label: 'Name Z-A', value: 'name-desc' },
      { label: 'Module A-Z', value: 'module-asc' },
      { label: 'Module Z-A', value: 'module-desc' },
    ],
  },
  'audit-log': {
    key: 'audit-log',
    group: 'Access Control',
    label: 'Audit Log',
    entityLabel: 'Audit Log',
    title: 'Audit Log',
    description: 'Every logged action across the system, with who did it and when.',
    apiBase: `${API_ROOT}/audit`,
    searchFields: [],
    defaultSort: { sortBy: 'timestamp', order: 'DESC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'audit',
    fields: [],
    columns: [],
    sortOptions: [],
  },
  settings: {
    key: 'settings',
    group: 'Access Control',
    label: 'Print Page Setup',
    entityLabel: 'Setting',
    title: 'Print Page Setup',
    description: 'Configure the page size and margins used when printing documents.',
    apiBase: `${API_ROOT}/misc/settings`,
    searchFields: [],
    defaultSort: { sortBy: 'key', order: 'ASC' },
    createButtonLabel: '',
    saveButtonLabel: '',
    emptyState: { title: '', description: '' },
    renderType: 'settings',
    fields: [],
    columns: [],
    sortOptions: [],
  },
};

export const MASTER_DATA_SECTION_ORDER = ['Master Data', 'Procurement', 'Sales', 'Inventory', 'Finance', 'Access Control'];

export const MASTER_DATA_MODULE_ORDER = [
  'categories',
  'products',
  'product-types',
  'suppliers',
  'customers',
  'warehouses',
  'accounts',
  'payment-methods',
  'purchase-orders',
  'purchase-vouchers',
  'sale-orders',
  'sales-invoices',
  'delivery',
  'production-batches',
  'stock-transfers',
  'stock-adjustments',
  'stock-count',
  'income-expense-categories',
  'finance-entries',
  'finance-transfers',
  'finance-ledger',
  'roles',
  'permissions',
  'audit-log',
  'settings',
];

export const MODULE_LOOKUP_MAP = MASTER_DATA_MODULE_ORDER.reduce((accumulator, key) => {
  accumulator[key] = MASTER_DATA_MODULES[key];
  return accumulator;
}, {});
